# Generated by Django 5.1.4 on 2025-02-05 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('valid_from', models.DateTimeField(verbose_name='Дійсний з')),
                ('valid_to', models.DateTimeField(verbose_name='Дійсний до')),
                ('discount', models.IntegerField(help_text='Відсоток знижки (від 0 дл 100)', validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Знижка')),
                ('active', models.BooleanField(verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Купон',
                'verbose_name_plural': 'Купони',
            },
        ),
    ]
